# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-15 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0006_animal'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
                ('a_m', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='if_delete',
            field=models.BooleanField(default=False),
        ),
    ]
