# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-15 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0007_auto_20200415_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='if_delete',
            new_name='is_delete',
        ),
    ]
