# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-19 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_price',
            field=models.IntegerField(default=1),
        ),
    ]
