"""
Django settings for Tail project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ja*^*$2n7++)!tf2ky26xjjt6f$np@fsq@7p$7cjq447bj45w*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'App',
    'Two',
    'sendemail',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Tail.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tail.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Tail',
        'USER': 'root',
        'PASSWORD': 'Ek#KpRGzIL3SKU#h',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

CACHES = {
    'default':{
        'BACKEND':'django_redis.cache.RedisCache',
        'LOCATION':'redis://127.0.0.1:6379/1',
        'OPTIONS':{
            'CLIENT_CLASS':'django_redis.client.DefaultClient',
        },
        'TIMEOUT':60*60*2,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

SUPER_USERS = ('Roc','root')

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES':(
        # "from rest_framework.throttling.UserRateThrottle",
        "Two.throttles.UserThrottle",
    ),
    'DEFAULT_THROTTLE_RATES':{
        'user':'5/m',
        'addr':'5/m',
    }
}


CELERY_BROKER_URL = 'redis://localhost:6379/1'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

#发送邮件的邮箱
EMAIL_HOST_USER = 'emoqyf@163.com'
EMAIL_HOST_PASSWORD = 'WWNCBRXUBSQUPEOQ'
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 465
#因为使用了端口号465（添加安全的端口，465或994），因此这里要设置SSL为True
EMAIL_USE_SSL = True
#因为端口是465，所以不需要使用TLS，具体查百度
# EMAIL_USE_TLS = True

EMAIL_FROM = 'emoqyf@163.com'

#配置日志
LOGGING_DIR = "logs"
if not os.path.exists(LOGGING_DIR):
    os.mkdir(LOGGING_DIR)
import logging
LOGGING = {
    'version':1,
    'disable_existing_loggers':False,
    'formatters':{
        'standard':{
            'format':'[%(levelname)s][%(asctime)s][%(filename)s][%(funcName)s][%(lineno)d] > %(message)s'
        },
        'simple':{
            'format':'[%(levelname)s] > %(message)s'
        },
    },
    'filters':{
        'require_debug_true':{
            '()':'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers':{
        'console':{
            'level':'DEBUG',
            'filters':['require_debug_true'],
            'class':'logging.StreamHandler',
            'formatter':'simple',
        },
        'file_handler':{
            'level':'INFO',
            'class':'logging.handlers.TimedRotatingFileHandler',
            'filename':'%s/django.log' % LOGGING_DIR,
            'formatter':'standard',
        },
        'mail_admins':{
            'level':'ERROR',
            'class':'django.utils.log.AdminEmailHandler',
            'formatter':'standard',
        },
    },
    'loggers':{
        'mydjango':{
            'handlers':['console','file_handler'],
            'level':'DEBUG',
            #propagate表示是否上传到上级文件，上级指的是上一级，例如debug上一级是info
            'propagate':True,
        },
        'django.request':{
            'handlers':['mail_admins','file_handler'],
            'level':'INFO',
            'propagate':False,
        },
        #如果要将get，post请求写到日志中，名字必须叫django，然后写到handler中
        'django':{
            'handlers':['console',],
            'level':'INFO',
            'propagate':False,
        }
    }
}