# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0002_auto_20200428_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='a_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_list', to='Two.UserModel'),
        ),
    ]
