# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-27 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testGenericForeignKey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='u_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testGenericForeignKey.Group'),
        ),
    ]
